export const cssColors = [
  {name: 'AliceBlue', hex: '#F0F8FF'},
  {name: 'AntiqueWhite', hex: '#FAEBD7'},
  {name: 'Aqua', hex: '#00FFFF'},
  {name: 'Aquamarine', hex: '#7FFFD4'},
  {name: 'Azure', hex: '#F0FFFF'},
  {name: 'Beige', hex: '#F5F5DC'},
  {name: 'Bisque', hex: '#FFE4C4'},
  {name: 'Black', hex: '#000000'},
  {name: 'BlanchedAlmond', hex: '#FFEBCD'},
  {name: 'Blue', hex: '#0000FF'},
  {name: 'BlueViolet', hex: '#8A2BE2'},
  {name: 'Brown', hex: '#A52A2A'},
  {name: 'BurlyWood', hex: '#DEB887'},
  {name: 'CadetBlue', hex: '#5F9EA0'},
  {name: 'Chartreuse', hex: '#7FFF00'},
  {name: 'Chocolate', hex: '#D2691E'},
  {name: 'Coral', hex: '#FF7F50'},
  {name: 'CornflowerBlue', hex: '#6495ED'},
  {name: 'Cornsilk', hex: '#FFF8DC'},
  {name: 'Crimson', hex: '#DC143C'},
  {name: 'Cyan', hex: '#00FFFF'},
  {name: 'DarkBlue', hex: '#00008B'},
  {name: 'DarkCyan', hex: '#008B8B'},
  {name: 'DarkGoldenRod', hex: '#B8860B'},
  {name: 'DarkGrey', hex: '#A9A9A9'},
  {name: 'DarkGreen', hex: '#006400'},
  {name: 'DarkKhaki', hex: '#BDB76B'},
  {name: 'DarkMagenta', hex: '#8B008B'},
  {name: 'DarkOliveGreen', hex: '#556B2F'},
  {name: 'DarkOrange', hex: '#FF8C00'},
  {name: 'DarkOrchid', hex: '#9932CC'},
  {name: 'DarkRed', hex: '#8B0000'},
  {name: 'DarkSalmon', hex: '#E9967A'},
  {name: 'DarkSeaGreen', hex: '#8FBC8F'},
  {name: 'DarkSlateBlue', hex: '#483D8B'},
  {name: 'DarkSlateGrey', hex: '#2F4F4F'},
  {name: 'DarkTurquoise', hex: '#00CED1'},
  {name: 'DarkViolet', hex: '#9400D3'},
  {name: 'DeepPink', hex: '#FF1493'},
  {name: 'DeepSkyBlue', hex: '#00BFFF'},
  {name: 'DimGrey', hex: '#696969'},
  {name: 'DodgerBlue', hex: '#1E90FF'},
  {name: 'FireBrick', hex: '#B22222'},
  {name: 'FloralWhite', hex: '#FFFAF0'},
  {name: 'ForestGreen', hex: '#228B22'},
  {name: 'Fuchsia', hex: '#FF00FF'},
  {name: 'Gainsboro', hex: '#DCDCDC'},
  {name: 'GhostWhite', hex: '#F8F8FF'},
  {name: 'Gold', hex: '#FFD700'},
  {name: 'GoldenRod', hex: '#DAA520'},
  {name: 'Grey', hex: '#808080'},
  {name: 'Green', hex: '#008000'},
  {name: 'GreenYellow', hex: '#ADFF2F'},
  {name: 'HoneyDew', hex: '#F0FFF0'},
  {name: 'HotPink', hex: '#FF69B4'},
  {name: 'IndianRed', hex: '#CD5C5C'},
  {name: 'Indigo', hex: '#4B0082'},
  {name: 'Ivory', hex: '#FFFFF0'},
  {name: 'Khaki', hex: '#F0E68C'},
  {name: 'Lavender', hex: '#E6E6FA'},
  {name: 'LavenderBlush', hex: '#FFF0F5'},
  {name: 'LawnGreen', hex: '#7CFC00'},
  {name: 'LemonChiffon', hex: '#FFFACD'},
  {name: 'LightBlue', hex: '#ADD8E6'},
  {name: 'LightCoral', hex: '#F08080'},
  {name: 'LightCyan', hex: '#E0FFFF'},
  {name: 'LightGoldenRodYellow', hex: '#FAFAD2'},
  {name: 'LightGrey', hex: '#D3D3D3'},
  {name: 'LightGreen', hex: '#90EE90'},
  {name: 'LightPink', hex: '#FFB6C1'},
  {name: 'LightSalmon', hex: '#FFA07A'},
  {name: 'LightSeaGreen', hex: '#20B2AA'},
  {name: 'LightSkyBlue', hex: '#87CEFA'},
  {name: 'LightSlateGrey', hex: '#778899'},
  {name: 'LightSteelBlue', hex: '#B0C4DE'},
  {name: 'LightYellow', hex: '#FFFFE0'},
  {name: 'Lime', hex: '#00FF00'},
  {name: 'LimeGreen', hex: '#32CD32'},
  {name: 'Linen', hex: '#FAF0E6'},
  {name: 'Magenta', hex: '#FF00FF'},
  {name: 'Maroon', hex: '#800000'},
  {name: 'MediumAquaMarine', hex: '#66CDAA'},
  {name: 'MediumBlue', hex: '#0000CD'},
  {name: 'MediumOrchid', hex: '#BA55D3'},
  {name: 'MediumPurple', hex: '#9370DB'},
  {name: 'MediumSeaGreen', hex: '#3CB371'},
  {name: 'MediumSlateBlue', hex: '#7B68EE'},
  {name: 'MediumSpringGreen', hex: '#00FA9A'},
  {name: 'MediumTurquoise', hex: '#48D1CC'},
  {name: 'MediumVioletRed', hex: '#C71585'},
  {name: 'MidnightBlue', hex: '#191970'},
  {name: 'MintCream', hex: '#F5FFFA'},
  {name: 'MistyRose', hex: '#FFE4E1'},
  {name: 'Moccasin', hex: '#FFE4B5'},
  {name: 'NavajoWhite', hex: '#FFDEAD'},
  {name: 'Navy', hex: '#000080'},
  {name: 'OldLace', hex: '#FDF5E6'},
  {name: 'Olive', hex: '#808000'},
  {name: 'OliveDrab', hex: '#6B8E23'},
  {name: 'Orange', hex: '#FFA500'},
  {name: 'OrangeRed', hex: '#FF4500'},
  {name: 'Orchid', hex: '#DA70D6'},
  {name: 'PaleGoldenRod', hex: '#EEE8AA'},
  {name: 'PaleGreen', hex: '#98FB98'},
  {name: 'PaleTurquoise', hex: '#AFEEEE'},
  {name: 'PaleVioletRed', hex: '#DB7093'},
  {name: 'PapayaWhip', hex: '#FFEFD5'},
  {name: 'PeachPuff', hex: '#FFDAB9'},
  {name: 'Peru', hex: '#CD853F'},
  {name: 'Pink', hex: '#FFC0CB'},
  {name: 'Plum', hex: '#DDA0DD'},
  {name: 'PowderBlue', hex: '#B0E0E6'},
  {name: 'Purple', hex: '#800080'},
  {name: 'RebeccaPurple', hex: '#663399'},
  {name: 'Red', hex: '#FF0000'},
  {name: 'RosyBrown', hex: '#BC8F8F'},
  {name: 'RoyalBlue', hex: '#4169E1'},
  {name: 'SaddleBrown', hex: '#8B4513'},
  {name: 'Salmon', hex: '#FA8072'},
  {name: 'SandyBrown', hex: '#F4A460'},
  {name: 'SeaGreen', hex: '#2E8B57'},
  {name: 'SeaShell', hex: '#FFF5EE'},
  {name: 'Sienna', hex: '#A0522D'},
  {name: 'Silver', hex: '#C0C0C0'},
  {name: 'SkyBlue', hex: '#87CEEB'},
  {name: 'SlateBlue', hex: '#6A5ACD'},
  {name: 'SlateGrey', hex: '#708090'},
  {name: 'Snow', hex: '#FFFAFA'},
  {name: 'SpringGreen', hex: '#00FF7F'},
  {name: 'SteelBlue', hex: '#4682B4'},
  {name: 'Tan', hex: '#D2B48C'},
  {name: 'Teal', hex: '#008080'},
  {name: 'Thistle', hex: '#D8BFD8'},
  {name: 'Tomato', hex: '#FF6347'},
  {name: 'Turquoise', hex: '#40E0D0'},
  {name: 'Violet', hex: '#EE82EE'},
  {name: 'Wheat', hex: '#F5DEB3'},
  {name: 'White', hex: '#FFFFFF'},
  {name: 'WhiteSmoke', hex: '#F5F5F5'},
  {name: 'Yellow', hex: '#FFFF00'},
  {name: 'YellowGreen', hex: '#9ACD32'},
]


export const crayolaColors = [
  {name: "Red",	hex: "#ED0A3F"},
  {name: "Maroon",	hex: "#C32148"},
  {name: "Scarlet",	hex: "#FD0E35"},
  {name: "Brick Red",	hex: "#C62D42"},
  {name: "English Vermilion",	hex: "#CC474B"},
  {name: "Madder Lake",	hex: "#CC3336"},
  {name: "Permanent Geranium Lake",	hex: "#E12C2C"},
  {name: "Maximum Red",	hex: "#D92121"},
  {name: "Indian Red",	hex: "#B94E48"},
  {name: "Orange-Red",	hex: "#FF5349"},
  {name: "Sunset Orange",	hex: "#FE4C40"},
  {name: "Bittersweet",	hex: "#FE6F5E"},
  {name: "Dark Venetian Red",	hex: "#B33B24"},
  {name: "Venetian Red",	hex: "#CC553D"},
  {name: "Light Venetian Red",	hex: "#E6735C"},
  {name: "Vivid Tangerine",	hex: "#FF9980"},
  {name: "Middle Red",	hex: "#E58E73"},
  {name: "Burnt Orange",	hex: "#FF7F49"},
  {name: "Red-Orange",	hex: "#FF681F"},
  {name: "Orange",	hex: "#FF8833"},
  {name: "Macaroni and Cheese",	hex: "#FFB97B"},
  {name: "Middle Yellow Red",	hex: "#ECB176"},
  {name: "Mango Tango",	hex: "#E77200"},
  {name: "Yellow-Orange",	hex: "#FFAE42"},
  {name: "Maximum Yellow Red",	hex: "#F2BA49"},
  {name: "Banana Mania",	hex: "#FBE7B2"},
  {name: "Maize",	hex: "#F2C649"},
  {name: "Orange-Yellow",	hex: "#F8D568"},
  {name: "Goldenrod",	hex: "#FCD667"},
  {name: "Dandelion",	hex: "#FED85D"},
  {name: "Yellow",	hex: "#FBE870"},
  {name: "Green-Yellow",	hex: "#F1E788"},
  {name: "Middle Yellow",	hex: "#FFEB00"},
  {name: "Olive Green",	hex: "#B5B35C"},
  {name: "Spring Green",	hex: "#ECEBBD"},
  {name: "Maximum Yellow",	hex: "#FAFA37"},
  {name: "Canary",	hex: "#FFFF99"},
  {name: "Lemon Yellow",	hex: "#FFFF9F"},
  {name: "Maximum Green Yellow",	hex: "#D9E650"},
  {name: "Middle Green Yellow",	hex: "#ACBF60"},
  {name: "Inchworm",	hex: "#AFE313"},
  {name: "Light Chrome Green",	hex: "#BEE64B"},
  {name: "Yellow-Green",	hex: "#C5E17A"},
  {name: "Maximum Green",	hex: "#5E8C31"},
  {name: "Asparagus",	hex: "#7BA05B"},
  {name: "Granny Smith Apple",	hex: "#9DE093"},
  {name: "Fern",	hex: "#63B76C"},
  {name: "Middle Green",	hex: "#4D8C57"},
  {name: "Green",	hex: "#3AA655"},
  {name: "Medium Chrome Green",	hex: "#6CA67C"},
  {name: "Forest Green",	hex: "#5FA777"},
  {name: "Sea Green",	hex: "#93DFB8"},
  {name: "Shamrock",	hex: "#33CC99"},
  {name: "Mountain Meadow",	hex: "#1AB385"},
  {name: "Jungle Green",	hex: "#29AB87"},
  {name: "Caribbean Green",	hex: "#00CC99"},
  {name: "Tropical Rain Forest",	hex: "#00755E"},
  {name: "Middle Blue Green",	hex: "#8DD9CC"},
  {name: "Pine Green",	hex: "#01786F"},
  {name: "Maximum Blue Green",	hex: "#30BFBF"},
  {name: "Robin's Egg Blue",	hex: "#00CCCC"},
  {name: "Teal Blue",	hex: "#008080"},
  {name: "Light Blue",	hex: "#8FD8D8"},
  {name: "Aquamarine",	hex: "#95E0E8"},
  {name: "Turquoise Blue",	hex: "#6CDAE7"},
  {name: "Outer Space",	hex: "#2D383A"},
  {name: "Sky Blue",	hex: "#76D7EA"},
  {name: "Middle Blue",	hex: "#7ED4E6"},
  {name: "Blue-Green",	hex: "#0095B7"},
  {name: "Pacific Blue",	hex: "#009DC4"},
  {name: "Cerulean",	hex: "#02A4D3"},
  {name: "Maximum Blue",	hex: "#47ABCC"},
  {name: "Blue (I)",	hex: "#4997D0"},
  {name: "Cerulean Blue",	hex: "#339ACC"},
  {name: "Cornflower",	hex: "#93CCEA"},
  {name: "Green-Blue",	hex: "#2887C8"},
  {name: "Midnight Blue",	hex: "#00468C"},
  {name: "Navy Blue",	hex: "#0066CC"},
  {name: "Denim",	hex: "#1560BD"},
  {name: "Blue (III)",	hex: "#0066FF"},
  {name: "Cadet Blue",	hex: "#A9B2C3"},
  {name: "Periwinkle",	hex: "#C3CDE6"},
  {name: "Blue (II)",	hex: "#4570E6"},
  {name: "Wild Blue Yonder",	hex: "#7A89B8"},
  {name: "Indigo",	hex: "#4F69C6"},
  {name: "Manatee",	hex: "#8D90A1"},
  {name: "Cobalt Blue",	hex: "#8C90C8"},
  {name: "Celestial Blue",	hex: "#7070CC"},
  {name: "Blue Bell",	hex: "#9999CC"},
  {name: "Maximum Blue Purple",	hex: "#ACACE6"},
  {name: "Violet-Blue",	hex: "#766EC8"},
  {name: "Blue-Violet",	hex: "#6456B7"},
  {name: "Ultramarine Blue",	hex: "#3F26BF"},
  {name: "Middle Blue Purple",	hex: "#8B72BE"},
  {name: "Purple Heart",	hex: "#652DC1"},
  {name: "Royal Purple",	hex: "#6B3FA0"},
  {name: "Violet (II)",	hex: "#8359A3"},
  {name: "Medium Violet",	hex: "#8F47B3"},
  {name: "Wisteria",	hex: "#C9A0DC"},
  {name: "Lavender (I)",	hex: "#BF8FCC"},
  {name: "Vivid Violet",	hex: "#803790"},
  {name: "Maximum Purple",	hex: "#733380"},
  {name: "Purple Mountains' Majesty",	hex: "#D6AEDD"},
  {name: "Fuchsia",	hex: "#C154C1"},
  {name: "Pink Flamingo",	hex: "#FC74FD"},
  {name: "Violet (I)",	hex: "#732E6C"},
  {name: "Brilliant Rose",	hex: "#E667CE"},
  {name: "Orchid",	hex: "#E29CD2"},
  {name: "Plum",	hex: "#8E3179"},
  {name: "Medium Rose",	hex: "#D96CBE"},
  {name: "Thistle",	hex: "#EBB0D7"},
  {name: "Mulberry",	hex: "#C8509B"},
  {name: "Red-Violet",	hex: "#BB3385"},
  {name: "Middle Purple",	hex: "#D982B5"},
  {name: "Maximum Red Purple",	hex: "#A63A79"},
  {name: "Jazzberry Jam",	hex: "#A50B5E"},
  {name: "Eggplant",	hex: "#614051"},
  {name: "Magenta",	hex: "#F653A6"},
  {name: "Cerise",	hex: "#DA3287"},
  {name: "Wild Strawberry",	hex: "#FF3399"},
  {name: "Lavender (II)",	hex: "#FBAED2"},
  {name: "Cotton Candy",	hex: "#FFB7D5"},
  {name: "Carnation Pink",	hex: "#FFA6C9"},
  {name: "Violet-Red",	hex: "#F7468A"},
  {name: "Razzmatazz",	hex: "#E30B5C"},
  {name: "Pig Pink",	hex: "#FDD7E4"},
  {name: "Carmine",	hex: "#E62E6B"},
  {name: "Blush",	hex: "#DB5079"},
  {name: "Tickle Me Pink",	hex: "#FC80A5"},
  {name: "Mauvelous",	hex: "#F091A9"},
  {name: "Salmon",	hex: "#FF91A4"},
  {name: "Middle Red Purple",	hex: "#A55353"},
  {name: "Mahogany",	hex: "#CA3435"},
  {name: "Melon",	hex: "#FEBAAD"},
  {name: "Pink Sherbert",	hex: "#F7A38E"},
  {name: "Burnt Sienna",	hex: "#E97451"},
  {name: "Brown",	hex: "#AF593E"},
  {name: "Sepia",	hex: "#9E5B40"},
  {name: "Fuzzy Wuzzy",	hex: "#87421F"},
  {name: "Beaver",	hex: "#926F5B"},
  {name: "Tumbleweed",	hex: "#DEA681"},
  {name: "Raw Sienna",	hex: "#D27D46"},
  {name: "Van Dyke Brown",	hex: "#664228"},
  {name: "Tan",	hex: "#D99A6C"},
  {name: "Desert Sand",	hex: "#EDC9AF"},
  {name: "Peach",	hex: "#FFCBA4"},
  {name: "Burnt Umber",	hex: "#805533"},
  {name: "Apricot",	hex: "#FDD5B1"},
  {name: "Almond",	hex: "#EED9C4"},
  {name: "Raw Umber",	hex: "#665233"},
  {name: "Shadow",	hex: "#837050"},
  {name: "Raw Sienna (I)",	hex: "#E6BC5C"},
  {name: "Timberwolf",	hex: "#D9D6CF"},
  {name: "Gold (I)",	hex: "#92926E"},
  {name: "Gold (II)",	hex: "#E6BE8A"},
  {name: "Silver",	hex: "#C9C0BB"},
  {name: "Copper",	hex: "#DA8A67"},
  {name: "Antique Brass",	hex: "#C88A65"},
  {name: "Black",	hex: "#000000"},
  {name: "Charcoal Gray",	hex: "#736A62"},
  {name: "Gray",	hex: "#8B8680"},
  {name: "Blue-Gray",	hex: "#C8C8CD"},
  {name: "Radical Red",	hex: "#FF355E"},
  {name: "Wild Watermelon",	hex: "#FD5B78"},
  {name: "Outrageous Orange",	hex: "#FF6037"},
  {name: "Atomic Tangerine",	hex: "#FF9966"},
  {name: "Neon Carrot",	hex: "#FF9933"},
  {name: "Sunglow",	hex: "#FFCC33"},
  {name: "Laser Lemon",	hex: "#FFFF66"},
  {name: "Unmellow Yellow",	hex: "#FFFF66"},
  {name: "Electric Lime",	hex: "#CCFF00"},
  {name: "Screamin' Green",	hex: "#66FF66"},
  {name: "Magic Mint",	hex: "#AAF0D1"},
  {name: "Blizzard Blue",	hex: "#50BFE6"},
  {name: "Shocking Pink",	hex: "#FF6EFF"},
  {name: "Razzle Dazzle Rose",	hex: "#EE34D2"},
  {name: "Hot Magenta",	hex: "#FF00CC"},
  {name: "Purple Pizzazz",	hex: "#FF00CC"},
  {name: "Sizzling Red",	hex: "#FF3855"},
  {name: "Red Salsa",	hex: "#FD3A4A"},
  {name: "Tart Orange",	hex: "#FB4D46"},
  {name: "Orange Soda",	hex: "#FA5B3D"},
  {name: "Bright Yellow",	hex: "#FFAA1D"},
  {name: "Yellow Sunshine",	hex: "#FFF700"},
  {name: "Slimy Green",	hex: "#299617"},
  {name: "Green Lizard",	hex: "#A7F432"},
  {name: "Denim Blue",	hex: "#2243B6"},
  {name: "Blue Jeans",	hex: "#5DADEC"},
  {name: "Plump Purple",	hex: "#5946B2"},
  {name: "Purple Plum",	hex: "#9C51B6"},
  {name: "Sweet Brown",	hex: "#A83731"},
  {name: "Brown Sugar",	hex: "#AF6E4D"},
  {name: "Eerie Black",	hex: "#1B1B1B"},
  {name: "Black Shadows",	hex: "#BFAFB2"},
  {name: "Fiery Rose",	hex: "#FF5470"},
  {name: "Sizzling Sunrise",	hex: "#FFDB00"},
  {name: "Heat Wave",	hex: "#FF7A00"},
  {name: "Lemon Glacier",	hex: "#FDFF00"},
  {name: "Spring Frost",	hex: "#87FF2A"},
  {name: "Absolute Zero",	hex: "#0048BA"},
  {name: "Winter Sky",	hex: "#FF007C"},
  {name: "Frostbite",	hex: "#E936A7"},
  {name: "Alloy Orange",	hex: "#C46210"},
  {name: "B'dazzled Blue",	hex: "#2E5894"},
  {name: "Big Dip O' Ruby",	hex: "#9C2542"},
  {name: "Bittersweet Shimmer",	hex: "#BF4F51"},
  {name: "Blast Off Bronze",	hex: "#A57164"},
  {name: "Cyber Grape",	hex: "#58427C"},
  {name: "Deep Space Sparkle",	hex: "#4A646C"},
  {name: "Gold Fusion",	hex: "#85754E"},
  {name: "Illuminating Emerald",	hex: "#319177"},
  {name: "Metallic Seaweed",	hex: "#0A7E8C"},
  {name: "Metallic Sunburst",	hex: "#9C7C38"},
  {name: "Razzmic Berry",	hex: "#8D4E85"},
  {name: "Sheen Green",	hex: "#8FD400"},
  {name: "Shimmering Blush",	hex: "#D98695"},
  {name: "Sonic Silver",	hex: "#757575"},
  {name: "Steel Blue",	hex: "#0081AB"},
  {name: "Aztec Gold",	hex: "#C39953"},
  {name: "Burnished Brown",	hex: "#A17A74"},
  {name: "Cerulean Frost",	hex: "#6D9BC3"},
  {name: "Cinnamon Satin",	hex: "#CD607E"},
  {name: "Copper Penny",	hex: "#AD6F69"},
  {name: "Cosmic Cobalt",	hex: "#2E2D88"},
  {name: "Glossy Grape",	hex: "#AB92B3"},
  {name: "Granite Gray",	hex: "#676767"},
  {name: "Green Sheen",	hex: "#6EAEA1"},
  {name: "Lilac Luster",	hex: "#AE98AA"},
  {name: "Misty Moss",	hex: "#BBB477"},
  {name: "Mystic Maroon",	hex: "#AD4379"},
  {name: "Pearly Purple",	hex: "#B768A2"},
  {name: "Pewter Blue",	hex: "#8BA8B7"},
  {name: "Polished Pine",	hex: "#5DA493"},
  {name: "Quick Silver",	hex: "#A6A6A6"},
  {name: "Rose Dust",	hex: "#9E5E6F"},
  {name: "Rusty Red",	hex: "#DA2C43"},
  {name: "Shadow Blue",	hex: "#778BA5"},
  {name: "Shiny Shamrock",	hex: "#5FA778"},
  {name: "Steel Teal",	hex: "#5F8A8B"},
  {name: "Sugar Plum",	hex: "#914E75"},
  {name: "Twilight Lavender",	hex: "#8A496B"},
  {name: "Wintergreen Dream",	hex: "#56887D"},
  {name: "Baby Powder",	hex: "#FEFEFA"},
  {name: "Banana",	hex: "#FFD12A"},
  {name: "Blueberry",	hex: "#4F86F7"},
  {name: "Bubble Gum",	hex: "#FFD3F8"},
  {name: "Cedar Chest",	hex: "#C95A49"},
  {name: "Cherry",	hex: "#DA2647"},
  {name: "Chocolate",	hex: "#BD8260"},
  {name: "Coconut",	hex: "#FEFEFE"},
  {name: "Daffodil",	hex: "#FFFF31"},
  {name: "Dirt", hex:	"#9B7653"},
  {name: "Eucalyptus",	hex: "#44D7A8"},
  {name: "Fresh Air",	hex: "#A6E7FF"},
  {name: "Grape",	hex: "#6F2DA8"},
  {name: "Jelly Bean",	hex: "#DA614E"},
  {name: "Leather Jacket",	hex: "#253529"},
  {name: "Lemon",	hex: "#FFFF38"},
  {name: "Licorice",	hex: "#1A1110"},
  {name: "Lilac",	hex: "#DB91EF"},
  {name: "Lime",	hex: "#B2F302"},
  {name: "Lumber",	hex: "#FFE4CD"},
  {name: "New Car",	hex: "#214FC6"},
  {name: "Orange",	hex: "#FF8866"},
  {name: "Peach",	hex: "#FFD0B9"},
  {name: "Pine",	hex: "#45A27D"},
  {name: "Rose",	hex: "#FF5050"},
  {name: "Shampoo",	hex: "#FFCFF1"},
  {name: "Smoke",	hex: "#738276"},
  {name: "Soap",	hex: "#CEC8EF"},
  {name: "Strawberry",	hex: "#FC5A8D"},
  {name: "Tulip",	hex: "#FF878D"},
  {name: "Amethyst",	hex: "#64609A"},
  {name: "Citrine",	hex: "#933709"},
  {name: "Emerald",	hex: "#14A989"},
  {name: "Jade",	hex: "#469A84"},
  {name: "Jasper",	hex: "#D05340"},
  {name: "Lapis Lazuli",	hex: "#436CB9"},
  {name: "Malachite",	hex: "#469496"},
  {name: "Moonstone",	hex: "#3AA8C1"},
  {name: "Onyx",	hex: "#353839"},
  {name: "Peridot",	hex: "#ABAD48"},
  {name: "Pink Pearl",	hex: "#B07080"},
  {name: "Rose Quartz",	hex: "#BD559C"},
  {name: "Ruby",	hex: "#AA4069"},
  {name: "Sapphire",	hex: "#2D5DA1"},
  {name: "Smokey Topaz",	hex: "#832A0D"},
  {name: "Tiger's Eye",	hex: "#B56917"},
]